---
title: "04-normalization-dimred-clustering-viz"
editor_options: 
  chunk_output_type: console
---

# load libraries, set directories

```{r}
#| warning: false
library(SingleCellExperiment)
library(scater)
library(scran)
library(scuttle)
library(dplyr)
library(bluster)
library(scDblFinder)
library(ggplot2)

library(pheatmap)

processed_dir <- "data/processed"
```

# read in SCD

```{r}
sce <- readRDS(file.path(processed_dir,
                         "sce-LC026-after-clustering.rds"))
sce
```

# find markers

```{r}

rownames(sce) <- paste0(rowData(sce)$ID, ".",
                        rowData(sce)$Symbol)

fm <- findMarkers(sce, groups=colData(sce)$cluster,
                  test.type = "wilcox", direction = "up",
                  pval.type = "some")

plotUMAP(sce, colour_by="cluster")
plotUMAP(sce, colour_by="ENSMUSG00000028399.Ptprd")

plotExpression(sce, features="ENSMUSG00000028399.Ptprd",
               x = "cluster", colour_by = "cluster")

```

# Viz

```{r}
genes <- unique(unlist(lapply(fm, 
                              function(u) rownames(u)[1:15])))
length(genes)

logcnts <- logcounts(sce)

o <- order(colData(sce)$cluster)

pheatmap(logcnts[genes,o], 
         cluster_cols = FALSE)

```

# save the dataset

```{r}
saveRDS(sce, file.path(processed_dir, "sce-LC026-after-clustering.rds"))
```

```{r}
sessionInfo()
```
