---
title: ""05-marker-genes"
editor_options: 
  chunk_output_type: console
---

# load libraries, set directories

```{r}
#| warning: false
library(SingleCellExperiment)
library(scater)
library(scran)
library(scuttle)
library(dplyr)
library(bluster)
library(scDblFinder)
library(ggplot2)

processed_dir <- "data/processed"
```

# read in SCD

```{r}
sce <- readRDS(file.path(processed_dir,
                         "sce-LC026-qc-filtered.rds"))
sce
```

# normalization, feature selection, dim reduction, clustering

```{r}
sce <- logNormCounts(sce)

mv <- modelGeneVar(sce)
hvgs <- getTopHVGs(mv, n=2000)

plot(mv$mean, mv$total)


sce <- runPCA(sce, subset_row = hvgs, ncomponents=30)



set.seed(3)
system.time(sce <- runUMAP(sce))


# clustering w/ Louvain
clust1 <- clusterCells(sce, use.dimred = "PCA",
                        BLUSPARAM = NNGraphParam(cluster.fun="louvain",
                                                 k=20))
colData(sce)$cluster <- clust1

# clustering w/ Pierre-Luc's kmeans+graph
system.time(clust2 <- fastcluster(sce))

table(clust1, clust2)
```

# Viz

```{r}
plotPCA(sce, colour_by="total")
plotPCA(sce, colour_by="subsets_MITO_percent")

plotUMAP(sce, colour_by="cluster", point_size=4)
```

# save the dataset

```{r}
saveRDS(sce, file.path(processed_dir, "sce-LC026-after-clustering.rds"))
```

```{r}
sessionInfo()
```
